/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalmartAutomationRouteImport } from './routes/walmart-automation'
import { Route as WalmartRouteImport } from './routes/walmart'
import { Route as TiktokShopRouteImport } from './routes/tiktok-shop'
import { Route as TiktokAutomationRouteImport } from './routes/tiktok-automation'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SellerOnboardingRouteImport } from './routes/seller-onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EbayAutomationRouteImport } from './routes/ebay-automation'
import { Route as EbayRouteImport } from './routes/ebay'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalmartIndexRouteImport } from './routes/walmart.index'
import { Route as TiktokShopIndexRouteImport } from './routes/tiktok-shop.index'
import { Route as EbayIndexRouteImport } from './routes/ebay.index'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as BlogStoriesSlugRouteImport } from './routes/blog_.stories.$slug'

const WalmartAutomationRoute = WalmartAutomationRouteImport.update({
  id: '/walmart-automation',
  path: '/walmart-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const WalmartRoute = WalmartRouteImport.update({
  id: '/walmart',
  path: '/walmart',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokShopRoute = TiktokShopRouteImport.update({
  id: '/tiktok-shop',
  path: '/tiktok-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokAutomationRoute = TiktokAutomationRouteImport.update({
  id: '/tiktok-automation',
  path: '/tiktok-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/seller-onboarding',
  path: '/seller-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EbayAutomationRoute = EbayAutomationRouteImport.update({
  id: '/ebay-automation',
  path: '/ebay-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const EbayRoute = EbayRouteImport.update({
  id: '/ebay',
  path: '/ebay',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalmartIndexRoute = WalmartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalmartRoute,
} as any)
const TiktokShopIndexRoute = TiktokShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TiktokShopRoute,
} as any)
const EbayIndexRoute = EbayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EbayRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStoriesSlugRoute = BlogStoriesSlugRouteImport.update({
  id: '/blog_/stories/$slug',
  path: '/blog/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ebay': typeof EbayRouteWithChildren
  '/ebay-automation': typeof EbayAutomationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-automation': typeof TiktokAutomationRoute
  '/tiktok-shop': typeof TiktokShopRouteWithChildren
  '/walmart': typeof WalmartRouteWithChildren
  '/walmart-automation': typeof WalmartAutomationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebay/': typeof EbayIndexRoute
  '/tiktok-shop/': typeof TiktokShopIndexRoute
  '/walmart/': typeof WalmartIndexRoute
  '/blog/stories/$slug': typeof BlogStoriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ebay-automation': typeof EbayAutomationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-automation': typeof TiktokAutomationRoute
  '/walmart-automation': typeof WalmartAutomationRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebay': typeof EbayIndexRoute
  '/tiktok-shop': typeof TiktokShopIndexRoute
  '/walmart': typeof WalmartIndexRoute
  '/blog/stories/$slug': typeof BlogStoriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/ebay': typeof EbayRouteWithChildren
  '/ebay-automation': typeof EbayAutomationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller-onboarding': typeof SellerOnboardingRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tiktok-automation': typeof TiktokAutomationRoute
  '/tiktok-shop': typeof TiktokShopRouteWithChildren
  '/walmart': typeof WalmartRouteWithChildren
  '/walmart-automation': typeof WalmartAutomationRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/ebay/': typeof EbayIndexRoute
  '/tiktok-shop/': typeof TiktokShopIndexRoute
  '/walmart/': typeof WalmartIndexRoute
  '/blog_/stories/$slug': typeof BlogStoriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/ebay'
    | '/ebay-automation'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/seller-onboarding'
    | '/services'
    | '/signup'
    | '/terms-of-service'
    | '/tiktok-automation'
    | '/tiktok-shop'
    | '/walmart'
    | '/walmart-automation'
    | '/blog/$slug'
    | '/ebay/'
    | '/tiktok-shop/'
    | '/walmart/'
    | '/blog/stories/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/ebay-automation'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/seller-onboarding'
    | '/services'
    | '/signup'
    | '/terms-of-service'
    | '/tiktok-automation'
    | '/walmart-automation'
    | '/blog/$slug'
    | '/ebay'
    | '/tiktok-shop'
    | '/walmart'
    | '/blog/stories/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/ebay'
    | '/ebay-automation'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy-policy'
    | '/reset-password'
    | '/seller-onboarding'
    | '/services'
    | '/signup'
    | '/terms-of-service'
    | '/tiktok-automation'
    | '/tiktok-shop'
    | '/walmart'
    | '/walmart-automation'
    | '/blog_/$slug'
    | '/ebay/'
    | '/tiktok-shop/'
    | '/walmart/'
    | '/blog_/stories/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EbayRoute: typeof EbayRouteWithChildren
  EbayAutomationRoute: typeof EbayAutomationRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TiktokAutomationRoute: typeof TiktokAutomationRoute
  TiktokShopRoute: typeof TiktokShopRouteWithChildren
  WalmartRoute: typeof WalmartRouteWithChildren
  WalmartAutomationRoute: typeof WalmartAutomationRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogStoriesSlugRoute: typeof BlogStoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/walmart-automation': {
      id: '/walmart-automation'
      path: '/walmart-automation'
      fullPath: '/walmart-automation'
      preLoaderRoute: typeof WalmartAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walmart': {
      id: '/walmart'
      path: '/walmart'
      fullPath: '/walmart'
      preLoaderRoute: typeof WalmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-shop': {
      id: '/tiktok-shop'
      path: '/tiktok-shop'
      fullPath: '/tiktok-shop'
      preLoaderRoute: typeof TiktokShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-automation': {
      id: '/tiktok-automation'
      path: '/tiktok-automation'
      fullPath: '/tiktok-automation'
      preLoaderRoute: typeof TiktokAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-onboarding': {
      id: '/seller-onboarding'
      path: '/seller-onboarding'
      fullPath: '/seller-onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebay-automation': {
      id: '/ebay-automation'
      path: '/ebay-automation'
      fullPath: '/ebay-automation'
      preLoaderRoute: typeof EbayAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebay': {
      id: '/ebay'
      path: '/ebay'
      fullPath: '/ebay'
      preLoaderRoute: typeof EbayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walmart/': {
      id: '/walmart/'
      path: '/'
      fullPath: '/walmart/'
      preLoaderRoute: typeof WalmartIndexRouteImport
      parentRoute: typeof WalmartRoute
    }
    '/tiktok-shop/': {
      id: '/tiktok-shop/'
      path: '/'
      fullPath: '/tiktok-shop/'
      preLoaderRoute: typeof TiktokShopIndexRouteImport
      parentRoute: typeof TiktokShopRoute
    }
    '/ebay/': {
      id: '/ebay/'
      path: '/'
      fullPath: '/ebay/'
      preLoaderRoute: typeof EbayIndexRouteImport
      parentRoute: typeof EbayRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/stories/$slug': {
      id: '/blog_/stories/$slug'
      path: '/blog/stories/$slug'
      fullPath: '/blog/stories/$slug'
      preLoaderRoute: typeof BlogStoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EbayRouteChildren {
  EbayIndexRoute: typeof EbayIndexRoute
}

const EbayRouteChildren: EbayRouteChildren = {
  EbayIndexRoute: EbayIndexRoute,
}

const EbayRouteWithChildren = EbayRoute._addFileChildren(EbayRouteChildren)

interface TiktokShopRouteChildren {
  TiktokShopIndexRoute: typeof TiktokShopIndexRoute
}

const TiktokShopRouteChildren: TiktokShopRouteChildren = {
  TiktokShopIndexRoute: TiktokShopIndexRoute,
}

const TiktokShopRouteWithChildren = TiktokShopRoute._addFileChildren(
  TiktokShopRouteChildren,
)

interface WalmartRouteChildren {
  WalmartIndexRoute: typeof WalmartIndexRoute
}

const WalmartRouteChildren: WalmartRouteChildren = {
  WalmartIndexRoute: WalmartIndexRoute,
}

const WalmartRouteWithChildren =
  WalmartRoute._addFileChildren(WalmartRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EbayRoute: EbayRouteWithChildren,
  EbayAutomationRoute: EbayAutomationRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TiktokAutomationRoute: TiktokAutomationRoute,
  TiktokShopRoute: TiktokShopRouteWithChildren,
  WalmartRoute: WalmartRouteWithChildren,
  WalmartAutomationRoute: WalmartAutomationRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogStoriesSlugRoute: BlogStoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
